// flow-typed signature: e0a359e4d48c1106a3f8b77134811839
// flow-typed version: <<STUB>>/seedrandom_v2.4.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'seedrandom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'seedrandom' {
  declare module.exports: any;
}

declare module 'seedrandom/seedrandom' {
  declare module.exports: any;
}

declare module 'seedrandom/seedrandom.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'seedrandom/index' {
  declare module.exports: $Exports<'seedrandom'>;
}
declare module 'seedrandom/index.js' {
  declare module.exports: $Exports<'seedrandom'>;
}
declare module 'seedrandom/seedrandom.js' {
  declare module.exports: $Exports<'seedrandom/seedrandom'>;
}
declare module 'seedrandom/seedrandom.min.js' {
  declare module.exports: $Exports<'seedrandom/seedrandom.min'>;
}

